---
- name: Shutdown rtorrent server
  hosts: torrent

  tasks:
  - name: shutdown rtorrent process
    become: true
    service:
      name: rtorrent@torrent
      state: stopped

  - name: unmount samba storage
    become: true
    command: umount /mnt/storage
   
  - name: shutdown
    become: true
    command: shutdown now
