---
- name: VyOS config
  connection: ansible.netcommon.network_cli
  hosts: device_roles_dn42_router
  tasks:
   - name: Push config
     vyos.vyos.vyos_config:
      lines:
       - delete protocols rpki cache 172.20.53.66
       - set protocols rpki cache 172.20.53.89 port 323
       - set protocols rpki cache 172.20.53.89 preference 1
...
